//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManiacEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class EditorState : global::System.Configuration.ApplicationSettingsBase {
        
        private static EditorState defaultInstance = ((EditorState)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EditorState())));
        
        public static EditorState Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool editEntitiesTransparency {
            get {
                return ((bool)(this["editEntitiesTransparency"]));
            }
            set {
                this["editEntitiesTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int lastQuickButtonState {
            get {
                return ((int)(this["lastQuickButtonState"]));
            }
            set {
                this["lastQuickButtonState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool movingPlatformsChecked {
            get {
                return ((bool)(this["movingPlatformsChecked"]));
            }
            set {
                this["movingPlatformsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool annimationsChecked {
            get {
                return ((bool)(this["annimationsChecked"]));
            }
            set {
                this["annimationsChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isPreRendering {
            get {
                return ((bool)(this["isPreRendering"]));
            }
            set {
                this["isPreRendering"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int developerInt {
            get {
                return ((int)(this["developerInt"]));
            }
            set {
                this["developerInt"] = value;
            }
        }
    }
}
