//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManiacEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class KeyBinds : global::System.Configuration.ApplicationSettingsBase {
        
        private static KeyBinds defaultInstance = ((KeyBinds)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new KeyBinds())));
        
        public static KeyBinds Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys NudgeFaster {
            get {
                return ((global::System.Windows.Forms.Keys)(this["NudgeFaster"]));
            }
            set {
                this["NudgeFaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys ScrollLock {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ScrollLock"]));
            }
            set {
                this["ScrollLock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys ScrollLockTypeSwitch {
            get {
                return ((global::System.Windows.Forms.Keys)(this["ScrollLockTypeSwitch"]));
            }
            set {
                this["ScrollLockTypeSwitch"] = value;
            }
        }
    }
}
